---
name: WWW-Sucksub-Frigo
version: 0.01
author:
  - Timothée Foucart <timothee.foucart@apinc.org>
abstract: ~
license: perl
requires:
  Alias: >=2.3
  Carp: >= 1.0
  DB_File: >= 1.8
  HTTP::Cookies: >= 1.3
  Test::More: >=0.5
  WWW::Mechanize: >= 1.02
provides:
  WWW::Sucksub::Frigo:
    file: lib/WWW/Sucksub/Frigo.pm
    version: 0.01
generated_by: Module::Build version 0.2611
